services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  GuzzleHttp\Client:
    autowire: true
    autoconfigure: true
    public: true

  #Each strategy must be tested individually to ensure it works correctly.
  #If you create more strategies for /coordinates endpoint. You should add them here.
  App\Controller\CoordinatesController.test.WholeStackStrategy:
    class: App\Controller\CoordinatesController
    arguments:
      $geocoderService: '@App\Service\GeocoderStrategy\WholeStackStrategy'

  App\Controller\CoordinatesController.test.GoogleStrategy:
    class: App\Controller\CoordinatesController
    arguments:
      $geocoderService: '@App\Service\GeocoderStrategy\GoogleStrategy'

  App\Controller\CoordinatesController.test.DatabasePlusHereStackStrategy:
    class: App\Controller\CoordinatesController
    arguments:
      $geocoderService: '@App\Service\GeocoderStrategy\DatabasePlusHereStackStrategy'
